// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TripManagerDart>>
abstract class TripManagerDart implements RustOpaqueInterface {
  /// The active trip's id, or `None` when no trip is running (#402).
  String? currentTripId();

  /// Returns true if a trip is actively being recorded.
  bool isTripActive();

  /// Initializes a new TripManager.
  factory TripManagerDart() =>
      RustLib.instance.api.crateApiDartTripTripManagerDartNew();

  /// Feeds a new location point to the trip manager.
  void onLocationReceived({
    required double latitude,
    required double longitude,
    required PlatformInt64 timestampMs,
  });

  /// Updates the motion state and reports the trip boundary it crossed, if
  /// any — `Started` with the new trip id, or `Ended` with the summary.
  TripTransitionDart? onMotionStateChanged({
    required bool isMoving,
    double? latitude,
    double? longitude,
    required PlatformInt64 timestampMs,
    required PlatformInt64 nowMs,
  });

  /// Resets the trip manager, discarding any active trip.
  void reset();
}

/// Contains the comprehensive data for a completed trip.
class TripDataDart {
  /// The UUIDv4 minted at trip start, shared with every record written
  /// during the trip (#402).
  final String tripId;
  final double distanceMeters;
  final double durationSeconds;

  /// Absolute trip bounds in epoch milliseconds (#402).
  final PlatformInt64 startedAtMs;
  final PlatformInt64 endedAtMs;
  final TripLocationDart? startLocation;
  final TripLocationDart? stopLocation;
  final List<TripWaypointDart> waypoints;

  const TripDataDart({
    required this.tripId,
    required this.distanceMeters,
    required this.durationSeconds,
    required this.startedAtMs,
    required this.endedAtMs,
    this.startLocation,
    this.stopLocation,
    required this.waypoints,
  });

  @override
  int get hashCode =>
      tripId.hashCode ^
      distanceMeters.hashCode ^
      durationSeconds.hashCode ^
      startedAtMs.hashCode ^
      endedAtMs.hashCode ^
      startLocation.hashCode ^
      stopLocation.hashCode ^
      waypoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripDataDart &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          distanceMeters == other.distanceMeters &&
          durationSeconds == other.durationSeconds &&
          startedAtMs == other.startedAtMs &&
          endedAtMs == other.endedAtMs &&
          startLocation == other.startLocation &&
          stopLocation == other.stopLocation &&
          waypoints == other.waypoints;
}

/// Represents a geographical location (start or stop) of a trip.
class TripLocationDart {
  final double latitude;
  final double longitude;

  const TripLocationDart({required this.latitude, required this.longitude});

  @override
  int get hashCode => latitude.hashCode ^ longitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripLocationDart &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude;
}

/// The moment a trip begins (#402).
class TripStartDart {
  final String tripId;
  final PlatformInt64 startedAtMs;
  final TripLocationDart? startLocation;

  const TripStartDart({
    required this.tripId,
    required this.startedAtMs,
    this.startLocation,
  });

  @override
  int get hashCode =>
      tripId.hashCode ^ startedAtMs.hashCode ^ startLocation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripStartDart &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          startedAtMs == other.startedAtMs &&
          startLocation == other.startLocation;
}

/// A trip boundary crossed by a motion state change (#402).
///
/// Exactly one of the two fields is set. This is a struct rather than the
/// sealed enum the native side uses because flutter_rust_bridge lowers a
/// payload-carrying enum to a `freezed` union, and pulling `freezed` and
/// `build_runner` into the plugin package is a steep price for one type.
/// uniffi has no such constraint, so Kotlin and Swift do get the real enum.
class TripTransitionDart {
  /// Set when this transition started a trip.
  final TripStartDart? started;

  /// Set when this transition ended one.
  final TripDataDart? ended;

  const TripTransitionDart({this.started, this.ended});

  @override
  int get hashCode => started.hashCode ^ ended.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripTransitionDart &&
          runtimeType == other.runtimeType &&
          started == other.started &&
          ended == other.ended;
}

/// Represents a single waypoint along a tracked trip.
class TripWaypointDart {
  final double latitude;
  final double longitude;
  final PlatformInt64 timestampMs;

  const TripWaypointDart({
    required this.latitude,
    required this.longitude,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      latitude.hashCode ^ longitude.hashCode ^ timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripWaypointDart &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          timestampMs == other.timestampMs;
}
