// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// An event generated when the battery budget engine decides to throttle or modify tracking parameters.
///
/// The field set is deliberately unchanged from the pre-ladder engine: it
/// crosses the flutter_rust_bridge boundary as well as the uniffi one, and its
/// wire layout is baked into committed generated code. The ladder's own
/// vocabulary lives on [`BudgetThrottleState`], which native hosts read through
/// [`BatteryBudgetEngine::throttle_state`].
class BudgetAdjustmentEvent {
  final double currentBatteryDrain;
  final double targetBudget;
  final double newDistanceFilter;
  final int newDesiredAccuracy;
  final int? newPeriodicInterval;

  const BudgetAdjustmentEvent({
    required this.currentBatteryDrain,
    required this.targetBudget,
    required this.newDistanceFilter,
    required this.newDesiredAccuracy,
    this.newPeriodicInterval,
  });

  @override
  int get hashCode =>
      currentBatteryDrain.hashCode ^
      targetBudget.hashCode ^
      newDistanceFilter.hashCode ^
      newDesiredAccuracy.hashCode ^
      newPeriodicInterval.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BudgetAdjustmentEvent &&
          runtimeType == other.runtimeType &&
          currentBatteryDrain == other.currentBatteryDrain &&
          targetBudget == other.targetBudget &&
          newDistanceFilter == other.newDistanceFilter &&
          newDesiredAccuracy == other.newDesiredAccuracy &&
          newPeriodicInterval == other.newPeriodicInterval;
}
